[package]
name = "buzz"
version = "0.1.0"
authors = ["taylor <taylor@jennifersoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systray = "0.4"
